### ISSUE TITLE
[TestEnv] MAC address to IP address resolution is a bit flaky

### ISSUE THREAD

**Issue by derkling** [ARM-software/lisa#12]
Reported by: Morten Rasmussen

Sometimes it is necessary to restart the notebook to fix it. It is currently unclear why.

**Comment by mdigiorgio** [comment]
This has been made more robust with #43. Should we consider it as closed?

**Comment by derkling** [comment]
Many improvements have been done on this topic... however a completely robust solution is almost impossible to get. For the time being what we have should be reasonable stable and since we have not got complains on that regard, let's try to close this issue.
