### ISSUE TITLE
Include a class diagram to help newcomers find their way around LISA

### ISSUE THREAD

**Issue by raw-bin** [ARM-software/lisa#124]
This suggestion came about in discussions around reducing the learning curve with LISA. It would be neat to have some autogenerated class diagrams to show the overall design hierarchy. Should help especially if folk want to extend LISA.

Perhaps this can then find it's way on the wiki in an automated fashion ?

**Comment by derkling** [comment]
Can this be something useful, or do we need to provide more details?
![screenshot_2016-07-20_19-22-39](https://cloud.githubusercontent.com/assets/63746/16997941/7644ea56-4eaf-11e6-81af-310c3f0e2ef6.png)

Maybe we can also add some links to the presentation and video I did at the Embedded Linux Conference.

**Comment by derkling** [comment]
I've updated the main Wiki page... have a look if it could be enough (for the time being) to close this issue.

**Comment by mdigiorgio** [comment]
Wiki looks nicer now :smile:

**Comment by derkling** [comment]
No feedbacks collected so far.... thus let's assume this issue be solved for the time being.
