### ISSUE TITLE
Vagrant: install wrapt

### ISSUE THREAD

**Issue by JaviMerino** [ARM-software/lisa#145]
latest devlib depend on wrapt.  The vagrant file should `pip install wrapt`.  I'd rather do this once #113 is merged rather than adding even more stuff there.

**Comment by bjackman** [comment]
Might it be easier to just use each lib's `setup.py`?

**Comment by mdigiorgio** [comment]
Yes, probably we could just pip install `bart`, `trappy` and `devlib`... @derkling what do you think?

**Comment by JaviMerino** [comment]
If we are going to pip install everything, then we should get rid of submodules.

**Comment by derkling** [comment]
Tough  decision... one more time.
If it simplify deployment on VMs, perhaps it's better to pip install everything... however, we must be aware that the LISA shell by default uses "DEVMOVE"... thus it expects local installed submodules...

**Comment by mdigiorgio** [comment]
OK, then let's just install dependencies when needed. I'll send a PR for solving this issue.

**Comment by derkling** [comment]
On 19-Jul 06:09, Michele Di Giorgio wrote:
> OK, then let's just install dependencies when needed. I'll send a PR
> for solving this issue.

Just to be clear, I'm open also to the other solution... only worried
for the changes required. We spent a lot of time to integrate
submodules... we just need to have a tought about what can be the
possible issues.

> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/ARM-software/lisa/issues/145#issuecomment-233626911

-- 
#include <best/regards.h>

Patrick Bellasi

**Comment by mdigiorgio** [comment]
Adding things is simple. IMHO it is probably better to solve this by using tags and provide users with a stable release (that has no dependency or other issues). This way, dependency issues will hopefully only appear in development versions.
