### ISSUE TITLE
How to capture trace.dat without wload

### ISSUE THREAD

**Issue by accsky** [ARM-software/lisa#1900]
How to  capture trace.dat only use FtraceCollector？
![image](https://user-images.githubusercontent.com/51768765/195525549-edf0e8bc-9f84-4abf-8421-bda1c97c8023.png)
thanks

**Comment by douglas-raillard-arm** [comment]
Hi @accksy, I'm not sure to understand the question. The trace.dat file will be created at the path pointed by output_path.

 If you are asking about how to just collect a trace without running a workload like in that example, simply don't use wload.run() and use time.sleep() or anything else you want to do while tracing.

**Comment by accsky** [comment]
Thanks, you got my point. This solved my problem.
