### ISSUE TITLE
cpu_capacity_orig goes away in kernel after Patch

### ISSUE THREAD

**Issue by credp** [ARM-software/lisa#2144]
In https://lore.kernel.org/all/20231009103621.374412-2-vincent.guittot@linaro.org/
the cpu_capacity_orig field is removed. This is related to the current issue of the load-tracking test not working. 

https://github.com/ARM-software/lisa/blob/627de71146862d516b62d8eef7ec89f740e40329/lisa/_assets/kmodules/lisa/sched_helpers.h#L217

**Comment by douglas-raillard-arm** [comment]
https://github.com/ARM-software/lisa/pull/2145
