### ISSUE TITLE
Remove necessity to use "bl" module on SMP platforms

### ISSUE THREAD

**Issue by bjackman** [ARM-software/lisa#218]
There is currently lots of code that assumes platforms are big.LITTLE (e.g. see references to "big" and "little" in libs/utils/trace.py, tests/eas/acceptance.py). To deal with this we use the "bl" module on platforms that aren't really big.LITTLE and just treat it as a big.LITTLE platform where big and LITTLE happen to be the same.

This is confusing and also sometimes breaks RTApp calibration - it errors out when the "LITTLE" cluster appears to be more powerful than the "big" cluster.

Furthermore, removing big.LITTLE assumptions will allow LISA to be used effectively with more exotic platforms.

**Comment by valschneider** [comment]
See https://github.com/ARM-software/lisa/issues/218
