### ISSUE TITLE
[Tests] Allows to filter the test configurations to run

### ISSUE THREAD

**Issue by derkling** [ARM-software/lisa#22]
Currently, tests/eas/rfc.py executes a test for all the workloads listed in the test configuration file.
It could be useful to add command line test option which allows to specify which workloads to run.
This specification should be provided as a generic regexp which will be used to filter the list of configuration defined workloads.

A similar command line option can be used to filter the target configurations.

**Comment by douglas-raillard-arm** [comment]
The issue is now solved by `exekall run --select` option
