### ISSUE TITLE
Remove ftrace setup duplication between Executor and Workload?

### ISSUE THREAD

**Issue by bjackman** [ARM-software/lisa#228]
Both `Executor` and `Workload` have code to handle ftrace collection. Haven't examined it properly but might be able to delete some code by having Executor just pass an ftrace object to `Workload::run`.

**Comment by valschneider** [comment]
My `Workload` implementation (https://github.com/valschneider/lisa/tree/tests/executor-rework) doesn't do any ftrace handling.
