### ISSUE TITLE
[Results] Improve stats for RTA PerfIndex metric

### ISSUE THREAD

**Issue by derkling** [ARM-software/lisa#24]
The current PerfIndex metric reports the average with respect to all the tasks composing the workload:
https://github.com/ARM-software/lisa/blob/master/libs/utils/results.py#L253

This could introduce big variances in case different tasks have quite different averages.
A better approach could be that to compute the average for each task independently.

A single metrics for the PerfIndex of an experiment can than be defined by ordering the per-task averages and comparing with respect to the same ordered list of the base case.
This should be enough to build a single index which better reports the performance index variation with respect to the base experiment.

**Comment by douglas-raillard-arm** [comment]
Closing as PerfIndex is currently available per-task in the rta analysis
