### ISSUE TITLE
Set up ADB USB udev permissions in Vagrantfile

### ISSUE THREAD

**Issue by bjackman** [ARM-software/lisa#248]
We should automatically add a [udev rules file](https://wiki.cyanogenmod.org/w/UDEV) in Vagrant VMs so that the vagrant user has permissions to access ADB devices.

**Comment by derkling** [comment]
Required rules are currently detailed at this link:
https://developer.android.com/studio/run/device.html

**Comment by douglas-raillard-arm** [comment]
Closing as this is very old and I don't think anyone is using vagrant at the moment.
