### ISSUE TITLE
[TestEnv] Add fast start mode

### ISSUE THREAD

**Issue by derkling** [ARM-software/lisa#28]
When we run a set of tests, the really first connection is usually required just to reboot the board to start with a new kernel. In this case the really first connection can avoid to initialize all the modules to be as fast as possible.

It can be useful to add a "fast mode" connection flag to the TestEnv module which grants only to have a valid SSH/ADB connection to the target without any other platform specific initializations.

**Comment by douglas-raillard-arm** [comment]
Closing as we don't currently reboot the board through LISA
