### ISSUE TITLE
[RFC] Add support to save execution logs into a file 

### ISSUE THREAD

**Issue by derkling** [ARM-software/lisa#29]
Currently we dump logging statements only on console. It can be useful in general to have a copy of the execution log statements also into a file produced in the same output folder.
The logging on file should not exclude console logging, which is still required possibly with a different logging level. Loglevel on file should be (by default) ad DEBUG level, since debug stataments can be easily filtered out offline.

**Comment by bjackman** [comment]
Implemented in https://github.com/ARM-software/lisa/pull/237 :)
