### ISSUE TITLE
Check frequency in load_tracking test

### ISSUE THREAD

**Issue by bjackman** [ARM-software/lisa#291]
As per [this discussion](https://github.com/ARM-software/lisa/pull/254#discussion_r100836848), the load_tracking test (currently a PR) assumes that the frequency we requested was actually used. Instead it may be worth having the test check the `cpu_frequency` events to ensure that the workload was actually executed at the frequency we expected.

**Comment by douglas-raillard-arm** [comment]
Load tracking is taking into account frequency nowadays
