### ISSUE TITLE
LisaTest.runTest creates spurious results

### ISSUE THREAD

**Issue by bjackman** [ARM-software/lisa#306]
I added a `runTest` method to LisaTest so that its subclasses could be instantiated conveniently. This is fine, but since nosetests discovers `runTest` as a test method it gets run (and always passes as it's empty) and produces a spurious result. E.g. for `tests/eas/heavy_load.py`:

```
test_tasks_spread (tests.eas.heavy_load.HeavyLoadTest) ... FAIL
runTest (tests.eas.heavy_load.LisaTest) ... ok
```

Can probably fix by removing `runTest` and instead overriding `__init__` in `LisaTest`. Or perhaps setting `LisaTest.runTest.__test__ = False`.

**Comment by derkling** [comment]
Was not that runTest method added to have a more clean interface when used from a Notebook?
If that's the case I would go for the second solution you proposed, just disable it for nosetests.
