### ISSUE TITLE
Stune :Negative Boost

### ISSUE THREAD

**Issue by divyalingaiah** [ARM-software/lisa#361]
Tried to apply negative boost of -20% in STUNE:smoke_test_ramp.config.
When I run lisa-test tests/stune/smoke_test_ramp.py ,It throws an error 
**"  self.assertTrue(analyzer.assertStatement(statement), msg=error_msg)
AssertionError: task was not boosted to the expected margin: -0.20"**

**Comment by bjackman** [comment]
Hi, what platform and kernel are you running?

**Comment by divyalingaiah** [comment]
On x86 platform and  4.10.0-android_ia_64 kernel.

**Comment by bjackman** [comment]
OK, do you think this is a LISA issue or a kernel issue?

**Comment by divyalingaiah** [comment]
Not really.Because when I try to run the base STUNE test without making any changes,the test runs succesfully.Only when I try to change BOOST values its erroring out
