### ISSUE TITLE
android: Add monkey-test workload

### ISSUE THREAD

**Issue by joelagnel** [ARM-software/lisa#385]
monkey tests are very useful doing lot of activity in short period of time on the device and collecting traces to analyze frame drops and other behavior. It would be nice to have a workload in workloads/ do this. I have something I'll post soon, this issue tracks it.

**Comment by bjackman** [comment]
It's worth noting that Workload Automation might be able to solve this use case already (some of the stuff we've been doing in LISA has been just because WA wasn't working with the latest Android, which may now be fixed).

**Comment by joelagnel** [comment]
Ok. maybe we're talking of different things? - this is basically the monkey apk launching an app and doing lots of activities (user interaction) to it, like 1000s of random touch, swipe events etc. The workload would essentially just call monkey.

**Comment by joelagnel** [comment]
@bjackman assign to me? (also let me know if/how I can assign to self)

**Comment by douglas-raillard-arm** [comment]
Closing as workloads are now in WA
