### ISSUE TITLE
android: Add camera workload

### ISSUE THREAD

**Issue by joelagnel** [ARM-software/lisa#386]
This feature is for tracking addition of camera workload to android.

**Comment by joelagnel** [comment]
How do I assign an issue to myself?

**Comment by joelagnel** [comment]
A simple test could just do the following:
        am force-stop com.google.android.GoogleCamera;
        sleep 1;
        am start -W -S -n com.google.android.GoogleCamera/com.android.camera.CameraLauncher;
        sleep 6;
        am start -a android.intent.action.MAIN -c android.intent.category.HOME;
        sleep 4;
        am force-stop com.google.android.GoogleCamera;
        sleep 1;

Later on we can add ability to take a camera shot and such things.

**Comment by valschneider** [comment]
https://github.com/ARM-software/lisa/pull/447
