### ISSUE TITLE
Add support/abstraction for running command-line scripts with LISA

### ISSUE THREAD

**Issue by joelagnel** [ARM-software/lisa#387]
@derkling @bjackman , just created this to track this feature. It is useful to have an abstraction to run LISA scripts from the command line to parse common command line arguments and provide a more well defined way to writing these scripts. Especially for Android, I think we'd want something like this for more easier data collection.

More specifically for Android I wanted something that could abstract common test parameters
--iterations=<number of iterations>
--workload=<workload-name eg youtube, jankbench>
--list_workloads
--collect=<power or systrace>
--collect_params=<energy meter name or systrace categories>
--serial_no=<dsn of device>
--outdir_name=<default to results/workload_timestamp> 

abstraction could look like class hierarchy Script -> AndroidScript etc.

**Comment by joelagnel** [comment]
I see this already there, maybe we want to improve/extend this?
https://github.com/ARM-software/lisa/blob/master/libs/utils/android/benchmark.py

**Comment by joelagnel** [comment]
Also, may be we can have a generic benchmark collector which you can pass a optional conf if needed?
So I should be able to say:
benchmark --workload=youtube --collect=energy 

I see benchmarks are their own python files, which call into workload.py (https://github.com/ARM-software/lisa/tree/master/tests/benchmarks), do we really need a separate python wrapper for each workload? CC: @ionela-voinescu @jlelli

**Comment by valschneider** [comment]
See https://github.com/ARM-software/lisa/pull/636
