### ISSUE TITLE
android: abstract workload collection params better

### ISSUE THREAD

**Issue by joelagnel** [ARM-software/lisa#388]
android workload.py's collection parameters are fixed, it would be useful if it can be parameterized, especially for systrace where you can pass it a set of parameters like trace-categories, or trace duration. Currently systrace collects fixed set of trace categories and no way to override this

**Comment by joelagnel** [comment]
Ignore comment about duration, rest of the comment stays

**Comment by douglas-raillard-arm** [comment]
Closing as workloads are handled in WA these days
