### ISSUE TITLE
Improve volume setting API

### ISSUE THREAD

**Issue by derkling** [ARM-software/lisa#401]
The volume setting API introduced by #398 is currently stateless.
We should extend it to allows the setting of a specified volume level.

**Comment by joelagnel** [comment]
I am told an app can be created to do this and the needed intents sent through adb. There isn't a direct adb way that works for older Android at the moment

**Comment by valschneider** [comment]
All of the Android APIs (should) now reside in devlib, so this no longer is a LISA issue.
