### ISSUE TITLE
Enable devlib loggers

### ISSUE THREAD

**Issue by bjackman** [ARM-software/lisa#402]
Devlib uses the `logging` module but we don't get any of the logs when using it via LISA. I spent 5 minutes fiddling but didn't figure out how to get them included in the LISA logs. Should figure this out. It should be obvious when reading the logs that the devlib ones come from devlib and not LISA itself.

**Comment by valschneider** [comment]
I think that one's no longer an issue, especially since we nicely format LISA's logs in lisa/next
