### ISSUE TITLE
Obtain the time spent in different CPU frequencies

### ISSUE THREAD

**Issue by joelagnel** [ARM-software/lisa#421]
@credp: Just mentioning the idea we discussed to obtain the time spent in different CPU frequencies as a LISA API. I think this would be very useful. Not sure if this should be in combination with a `devlib` module modification to fetch the data?

**Comment by bjackman** [comment]
Worth mentioning that there is already an API to do this from traces - `trace.data_frame.cluster_frequency_residency`, but I guess you're talking about using the kernels' own accounting as chris did.

**Comment by douglas-raillard-arm** [comment]
Seems like LISA is already able to do that in the `frequency` analysis
