### ISSUE TITLE
Make new devices work out of the box

### ISSUE THREAD

**Issue by valschneider** [ARM-software/lisa#425]
Having a new target device for LISA currently requires a bit of work, although the base requirements for a new device aren't that big.

It mostly all comes down to the platform file in **libs/utils/platforms/\<device-name\>.json**. The energy model can be fetched from the target, but post-processing usually requires the json file. This isn't entirely flawed logic, as it should be possible to run post-processing of traces without having access to the device itself, but maybe it should be handled differently. Here's a list of options:

- Do as much post-processing as possible without the platform file - this is what https://github.com/ARM-software/lisa/pull/342 & https://github.com/ARM-software/lisa/issues/427 are about.
- Export the platform description if it's not already there when running tests - we can get all of the information that we need from the device itself, so generating the platform description shouldn't be too hard. The tricky point is cleanly distinguishing big and LITTLE clusters.

**Comment by joelagnel** [comment]
+1

**Comment by valschneider** [comment]
Now that we have automated the devlib module loading, we've done good progress on this side. Now it's mostly about cleaning up analysis to not depend on hard-coded energy model values, but that's https://github.com/ARM-software/lisa/issues/427
