### ISSUE TITLE
Relax strict dependency of Trace from platform data

### ISSUE THREAD

**Issue by derkling** [ARM-software/lisa#427]
The Analysis API relays on DF generated by the Trace module, which currently enforce a strict dependency on platform data being available. Unfortunately these platform data are not always available. for example their are missing when traces are collected not using the standard LISA APIs for workloads execution.

Moreover, many plotting APIs have hard-coded assumption that Trace's generated DF have the additional data and columns generated by the availability of platform data.

To better support a broader usage of LISA we should remove this strict dependency from the `Trace` class by making "platform" an optional set of data as well as by making smarter (i.e. optional) any hard-coded dependency on platform data from the dataframe getters and plotting APIs.

**Comment by douglas-raillard-arm** [comment]
PlatformInfo is optional when building a trace nowadays
