### ISSUE TITLE
Add Hikey960 board support in LISA

### ISSUE THREAD

**Issue by cloverpop** [ARM-software/lisa#443]
Hikey960 board CPU topology
4 Cortex-A73 + 4 Cortex-A53

**Comment by cloverpop** [comment]
Patch is submitted.

**Comment by butterl** [comment]
@cloverpop 
> Patch is submitted.
Do you mean Hikey960 already supported by lisa ？ Do I need an extra  compile flag for it?

Thanks,
Butter

**Comment by bjackman** [comment]
@butterl I believe all you need to do is add `"board": "hikey960"`to your `target.config`.
