### ISSUE TITLE
Enhancement: Add a dummy energy meter class

### ISSUE THREAD

**Issue by cloverpop** [ARM-software/lisa#446]
If possible, please add a dummy energy meter class.

Currently, "hwmon"/"AEP"/"ACME" can be used for physical power consumption.
If the target board doesn't have any hardware energy meter ( e.g. hwmon/AEP/ACME), it's better for us to set a dummy energy meter module ( let's assume it "dummy_emeter" ), which can function as if it is a physical energy meter. 

Of course, all the test results reported by the dummy emeter are only for simulation and we don't care about the result validity.  It's perfect if the dummy emeter reports lower power consumption for LITTLE cpu and higher power consumption for big cpu.

Benefit: With this new module, we can easily demo some notebooks for energy analysis because in customer site, it is difficult to set up a workable AEP/ACME environment in demo time!

Please consider this enhancement.  Thanks.

**Comment by derkling** [comment]
Setting up an ACME in demo mode is pretty fast: you just need a USB connection to the ACME, which is used both to power it up as well as to reach it via the USB Ethernet interface it provides.

You can of course avoid connecting the ACME to the target, which will make you read random/noise samples... but still I consider this a better / more realistic setup to demo.

Can you consider this option and, in case you agree and don't have other more specific needs for a dummy EM, close this issue?
