### ISSUE TITLE
LISA installation readme change request

### ISSUE THREAD

**Issue by cloverpop** [ARM-software/lisa#476]
Reason:   python scipy package is mandatory to execute the lisa/ipynb/energy/EnergyModel_ClusterEnergy.ipynb notebook successfully. 
However, scipy is not documented in LISA installation guide. 
So please add it.

**Comment by cloverpop** [comment]
If possible, please also update this URL:  https://github.com/ARM-software/lisa/wiki/Installation about "Required dependencies"

**Comment by bjackman** [comment]
OK, I have updated the Wiki too.
