### ISSUE TITLE
System start_activity and start_action should allow -W parameter

### ISSUE THREAD

**Issue by mcgeagh** [ARM-software/lisa#483]
When performing an am start, i want to provide the -W parameter, as this waits and reports back useful timing statistics.

Suggestion: Add a parameter to start_activity and start_action functions in system.py to allow the use of the -W parameter.

Optionally: -S will first force-stop the app before attempting applaunch (i see that being useful - saves you having to do a force-stop command beforehand). Another optional parameter perhaps?

**Comment by douglas-raillard-arm** [comment]
The module being described is not part of LISA anymore
