### ISSUE TITLE
[RTA] Add support to per-phases calibration

### ISSUE THREAD

**Issue by derkling** [ARM-software/lisa#54]
The calibration value of an RTA generated workload cannot be defined to be something different on different phases. For example it's not possible to defined a task which generates 20% load of a LITTLE cpu for X seconds and than becomes a 40% of a big cpu.

Such a support is currently not provided by rt-app, which supports a single calibration value.
However, perhaps is still possible to use always the max calibration value for RTApp and scale appropriately the load demand to configure in the JSON file based on the ratio between big and little calibration values.

**Comment by valschneider** [comment]
This is pretty much what is done with https://github.com/ARM-software/lisa/blob/next/lisa/tests/kernel/scheduler/eas_behaviour.py#L377, so I'm closing this
