### ISSUE TITLE
Wltest setup bugs

### ISSUE THREAD

**Issue by qperret** [ARM-software/lisa#543]
When setting up wltest for the first time we noticed that the following problems are not caught:
 - it is possible to run lisa-wltest-series without having the virtualenv binary installed which leads to all sorts of errors. The presence of virtualenv should be checked in lisa-wltest-init
 - when there are permissions issues with fastboot (udev rules not set correctly, sudo rights needed, ...) the user will face the "timeout to reboot in bootloader" error. This should be caught with a better error message at least.

**Comment by douglas-raillard-arm** [comment]
This would be addressed by a revamp of wltest to make it more robust, closing for now as the actual task would have a larger scope
