### ISSUE TITLE
LISA test harness

### ISSUE THREAD

**Issue by joelagnel** [ARM-software/lisa#595]
This issue is to develop a single test execution framework (test harness) to use by LISA:

Currently we have 3 ways:
* executor
* Android experiments
* WA

We should have a single streamlined way of running a workload and collecting its data, than all these multiple ways.

Next, workloads can be any of the following:
- workload generator (wlgen)
- Android workloads (camera, uibench etc)
- Android behaviors (turn screen on/off)

Its best if all the above workloads are also in a single place, like WA.  The wlgen can probably be a devlib instrument or something, with a corresponding WA frontend.

This was discussed at ARM with @qperret  @valschneider and @douglas-raillard-arm . Please update the issue with anything I missed.

**Comment by joelagnel** [comment]
Yes sounds good, also probably that category can include wlgen stuff as well?

**Comment by douglas-raillard-arm** [comment]
Most likely, unless there are strong advantages to define a "pure" wlgen workload.

**Comment by valschneider** [comment]
I think that discussion can happen on the code itself now (see https://lisa-linux-integrated-system-analysis.readthedocs.io/en/next/kernel_tests.html#module-lisa.tests.kernel.test_bundle)
