### ISSUE TITLE
Setting sampling_rate for cpufreq gov's other than ondemand

### ISSUE THREAD

**Issue by deggeman** [ARM-software/lisa#60]
With the advent of utilization driven sugov we have to be able to also set its sampling_rate value via the appropriate sys file.

I have a patch which extends the appropriate functionality in libs/utils/executor.py but there is rumour that this code is deprecated in favour of functionality in devlib?

**Comment by derkling** [comment]
This is not more a LISA specific issue, thus going to close this one.
An issue has been posted for devlib:
https://github.com/ARM-software/devlib/issues/32
