### ISSUE TITLE
wlgen/rta.py: rt-app log files are being pulled from the wrong directory

### ISSUE THREAD

**Issue by v0lker** [ARM-software/lisa#659]
specifying a JSON config with `'logdir' : '/some/path'`, i would expect the log files to be retrieved from `/some/path`. instead, the `run_dir` is used:

RTA::__postrun():
``` 
logfile = self.target.path.join(self.run_dir, '*{}*.log'.format(task))
self.target.pull(logfile, destdir)
```

this seems to suggest that the `logdir` parameter effectively only works if it is set to the `run_dir`.

**Comment by valschneider** [comment]
It's not fixing your issue straight away, but FYI the whole theme of "some artifact wasn't generated where I expected it to" (sometimes in another directory than the one specified, sometimes no directory is specified so it's just whatever the current path is) was addressed in LISA/next.

So now you'd [specify some directory](https://github.com/ARM-software/lisa/blob/next/lisa/wlgen/rta.py#L47) (or get one assigned to you in the results/ directory) and everything would land there. For instance, [the log](https://github.com/ARM-software/lisa/blob/next/lisa/wlgen/rta.py#L109).
