### ISSUE TITLE
Vagrant: Wrong trace-cmd is being used

### ISSUE THREAD

**Issue by valschneider** [ARM-software/lisa#722]
Need to just use the one shipped in devlib, but I'm writing this here not to forget.

**Comment by douglas-raillard-arm** [comment]
Maybe we should add the devlib's tools to PATH, and remove our build of trace-cmd. At some point, it was considered a feature to give priority to the system's trace-cmd, in case you want to use your own (and potentially more up-to-date) version.

**Comment by douglas-raillard-arm** [comment]
Linked to https://github.com/ARM-software/lisa/pull/969
