### ISSUE TITLE
Need update devlib to fix Android adb connection

### ISSUE THREAD

**Issue by Leo-Yan** [ARM-software/lisa#78]
Hi there,

The devlib's new patch https://github.com/ARM-software/devlib/commit/6bda8cb86734eca4f1e589372824cfe607275d1c is to fix Android adb connection. So suggest to forward devlib's submodule's HEAD in LISA.

Thanks,
Leo Yan

**Comment by mdigiorgio** [comment]
We are waiting for the new TRAPpy release before updating all submodules' HEADs. By the end of the week they should be updated.

**Comment by Leo-Yan** [comment]
Thanks.
